name: Translate files using DeepL Translate GitHub Action
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Translate locales json
        uses: lyqht/deepl-translate-github-action@v2.0.0-beta
        with:
          target_languages: fr,ja,ko,zh,es
          input_file_path: locales/en.json
          output_file_name_prefix: locales/
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
      - name: Translate README
        uses: lyqht/deepl-translate-github-action@v2.0.0-beta
        with:
          target_languages: fr,ja,ko,zh,es
          input_file_path: README.md
          output_file_name_prefix: docs/
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
